jenkins:
  systemMessage: "Jenkins Test Environment - Configured automatically via JCasC"
  numExecutors: 4
  mode: NORMAL

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
        - id: "dev1"
          password: "dev1"
        - id: "dev2"
          password: "dev2"

  authorizationStrategy:
    projectMatrix:
      entries:
        - user:
            name: "admin"
            permissions:
              - "Overall/Administer"
              - "Overall/Read"
              - "Job/Read"
              - "Job/Build"
              - "Job/Configure"
              - "Job/Delete"
              - "Job/Discover"
              - "Job/Workspace"
              - "Run/Delete"
              - "Run/Replay"
              - "Run/Update"
              - "View/Read"
              - "View/Configure"
              - "View/Create"
              - "View/Delete"
              - "SCM/Tag"
        - group:
            name: "authenticated"
            permissions:
              - "Overall/Read"
              - "Job/Discover"

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-pat"
              username: "${GITHUB_USERNAME}"
              password: "${GITHUB_PAT}"
              description: "GitHub PAT for multibranch pipelines"

unclassified:
  location:
    url: http://localhost:8080/

jobs:
  - file: /var/jenkins_home/jobs-dsl/pipeline.groovy
